config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'posts', to: 'posts#index'
  get 'posts/new', to: 'posts#new'
  post 'posts', to: 'posts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
  end

  def create
    Post.create(post_params)
  end

  private
  def post_params
    params.permit(:contents)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="top">
    <%= link_to posts_path do %>
      <h1>My First Appの復習</h1>
    <% end %>
    <%= link_to posts_new_path do %>
      <div class="btn">新規投稿</div>
    <% end %>
  </header>
    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1 class="create">投稿が完了しました</h1>
<%= link_to posts_path do %>
  <div class="notice">TOPに戻る</div>
<% end %>

app/views/posts/index.html.erb
<div class="content">投稿一覧
  <% @posts.each do |post|%>
    <div class="post">
      <div class="date">投稿日：
        <%= post.created_at %>
      </div>
      <div class="txt">
        <%= post.content %>
      </div>
    </div>
  <% end%>
</div>

app/views/posts/new.html.erb
<h1 class="new">新規投稿ページ</h1>
<%= form_tag('posts', method: :post) do %>
  <input type = "text" name = "content">
  <input type = "submit" value = "投稿する">
<% end %>